# Generated by Django 4.1.7 on 2023-04-09 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userclothes',
            name='user_id',
        ),
        migrations.AddField(
            model_name='userclothes',
            name='userID',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userclothes',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
