# Generated by Django 4.1.7 on 2023-04-09 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_userclothes_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userclothes',
            name='user_id',
            field=models.CharField(max_length=50),
        ),
    ]
