# Generated by Django 4.1.7 on 2023-03-22 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloth_name', models.CharField(max_length=200)),
                ('cloth_var', models.CharField(max_length=200)),
                ('cloth_col_1', models.CharField(max_length=200)),
                ('cloth_col_2', models.CharField(max_length=200)),
            ],
        ),
    ]
